### ISSUE TITLE
Timeline & TODOS

### ISSUE THREAD

**Issue by evenstensberg** [sheerun/bower-away#1]
Could we get up a list over what needs to be done to get this ready so collaborators could follow up and make PR's?

**Comment by sheerun** [comment]
want to do it? as a final goal one is able to convert any bower project to using yarn

**Comment by evenstensberg** [comment]
I can pick up some of the stuff mentioned at the thread at Bower and transfer them here if that's okay?

**Comment by sheerun** [comment]
OK

**Comment by sheerun** [comment]
I think basic version is done. We can open new issues for things to improve
