### ISSUE TITLE
.bowerrc support.

### ISSUE THREAD

**Issue by danvickers** [sheerun/bower-away#11]
Is there a way to get this to respect our .bowerrc file so that we can use a private cache of the bower repository?

**Comment by sheerun** [comment]
what .bowerrc contents are you talking about?

**Comment by GabLeRoux** [comment]
https://bower.io/docs/config/

I think the most common usage of it is `"directory":` where one can specify the `bower_components` destination.

I am actually facing this as I'd like to get bower libs into my `assets/vendors` folder instead of `node_modules`. Based on https://bower.io/blog/2017/how-to-migrate-away-from-bower/ 
> hough you can link it somewhere else in postinstall script

That would be the solution, but I don't know what's the best way to **link** `node_modules/@bower_componets` to `assets/vendors` for example.

Similar to #9 I don't want to break things on windows.

**Comment by sheerun** [comment]
@GabLeRoux do following work on windows? `node -e 'require("fs").symlinkSync("../node_modules/@bower_components", "vendor/assets")'`

**Comment by GabLeRoux** [comment]
I spinned a windows vm for this.

* Windows 10
* Installed node 8.11.14 LTS

**Using powershell** _had problems with `git bash` and bower: https://github.com/bower/bower/issues/802_

```bash
mkdir temp
cd temp
mkdir -p assets/vendor
npm init
npm i -g bower bower-away
bower init
```

`.bowerrc`:
```javascript
{
    "directory": "assets/vendor"
}
```

```bash
bower install --save font-awesome
npm i -g yarn
bower-away --apply
```

```diff
diff --git a/package.json b/package.json
index 4c1aca6..00eeefe 100644
--- a/package.json
+++ b/package.json
@@ -7,5 +7,11 @@
   },
   "author": "",
   "license": "ISC",
-  "description": ""
+  "description": "",
+  "dependencies": {
+    "@bower_components/font-awesome": "FortAwesome/Font-Awesome#^4.7.0"
+  },
+  "engines": {
+    "yarn": ">= 1.0.0"
+  }
 }
```

👍 

`package.json`:
```javascript
{
  "name": "temp",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
	"postinstall": "node -e 'require(\"fs\").symlinkSync(\"node_modules/@bower_components\", \"assets/vendor\")'"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "@bower_components/font-awesome": "FortAwesome/Font-Awesome#^4.7.0"
  },
  "engines": {
    "yarn": ">= 1.0.0"
  }
}

```

```bash
yarn install
```

## result
```
PS C:\Users\IEUser\temp> yarn install
yarn install v1.2.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ node -e 'require("fs").symlinkSync("node_modules/@bower_components", "assets/vendor")'
[eval]:1
'require(fs).symlinkSync(node_modules/@bower_components,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at evalScript (bootstrap_node.js:347:27)
    at run (bootstrap_node.js:122:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:121:9)
    at bootstrap_node.js:496:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

_note that `yarn install` does succeed when removing the `postinstall` script so `package.json` is valid ;)_

I also tried manually:
```
PS C:\Users\IEUser\temp> node -e 'require("fs").symlinkSync("node_modules/\@bower_components", "assets/vendor")'
[eval]:1
require(fs).symlinkSync(node_modules/\@bower_components, assets/vendor)
                                     ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at evalScript (bootstrap_node.js:347:27)
    at run (bootstrap_node.js:122:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:121:9)
    at bootstrap_node.js:496:3
```

**Comment by GabLeRoux** [comment]
So quotes and double quotes are important here. I managed to get the command executing, but only with **powershell ran as administrator** with the following (not inside `package.json` yet):

```bash
rmdir assets/vendor
rm assets/vendor
mkdir assets
node -e "require('fs').symlinkSync('node_modules/@bower_components', 'assets/vendor')"
```

But it only generates a `vendor` symlink file that seems invalid:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/1264761/31665912-743e0c28-b318-11e7-8367-12a602ed75bb.png">

I'd let someone with more windows experience try things here, but I feel like pushing people to migrate to yarn without being able to support windows will be a pain. I'm glad I'm not using windows on a daily basis eh.

**Comment by sheerun** [comment]
I guess somebody needs to create cross-platform package for linking then

**Comment by sheerun** [comment]
I've heard that symlinks on windows require admin access, but junctions not

**Comment by samypr100** [comment]
This worked for me on Linux, Mac, and Windows as a postinstall script:
```node
node -e "require('fs').symlinkSync(require('path').join(process.cwd(), 'node_modules/@bower_components'), require('path').join(process.cwd(), 'public/assets/vendor'), 'junction')"
```

**Comment by sheerun** [comment]
@samypr100 Thanks for sharing! I'll update bower-away

**Comment by GabLeRoux** [comment]
I also confirm it worked using `poweshell` ran as administrator on windows 10.  
Good job @samypr100 👍 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/1264761/31789623-b198d660-b4e0-11e7-8695-0f5ec3cc1792.png">

```powershell
dir .\public\assets\vendor\

    Directory: C:\Users\IEUser\temp\public\assets\vendor
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/17/2017   5:32 AM                font-awesome
```

**Comment by sheerun** [comment]
@samypr100 Would following also work on windows?

```
node -e "require('fs').symlinkSync(require('path').join(process.cwd(), 'node_modules/@bower_components'), 'public/assets/vendor', 'junction')"
```

**Comment by sheerun** [comment]
Sorry, following:

```
node -e "require('fs').symlinkSync(require('path').resolve('node_modules/@bower_components'), 'public/assets/vendor', 'junction')"
```

**Comment by GabLeRoux** [comment]
```powershell
PS C:\Users\IEUser\temp> node -e "require('fs').symlinkSync(require('path').resolve('node_modules/@bower_components'), 'public/assets/vendor', 'junction')"
PS C:\Users\IEUser\temp> dir .\public\assets\vendor\


    Directory: C:\Users\IEUser\temp\public\assets\vendor


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/19/2017   1:21 PM                font-awesome
```

I'd say yes. (I deleted `public\assets\vendor` first and tried the above) 👍

**Comment by sheerun** [comment]
@GabLeRoux Thanks! I've updated and released bower-away with this change.

Given that this one is solved and original author of issue is not responsive, I'm closing it.
