### ISSUE TITLE
Running in loop

### ISSUE THREAD

**Issue by pawamoy** [sheerun/bower-away#14]
So I installed yarn with `sudo npm install -g yarn`, and then bower-away with `yarn global add bower-away`. But I had no exec called bower-away in my PATH so I installed it again with `sudo npm install -g bower-away` and I am now able to call it.

Now I go into my static folder, where my bower.json and bower_components are, and run bower-away.

```
$ bower-away 

# Remove old components directory

Now, please remove original components directory:
$ rm -rf bower_components

Please call bower-away once more when you're done with this!
```

Ok, deleted the folder.

```
$ bower-away 

# Install dependencies with Bower

We need to install dependencies the old way first. Please run:
$ bower install

At the end you should see some packages in:
/media/pawamoy/Data/git/genida/genida/static/bower_components

Please call bower-away once more when you're done with this!
```

Ok, ran bower install.

```
$ bower-away 

# Remove old components directory

Now, please remove original components directory:
$ rm -rf bower_components

Please call bower-away once more when you're done with this!
```

...

It goes on like this, making me install then delete bower components over and over again 😆

**Comment by sheerun** [comment]
Thanks for reporting, I've fixed it. npm upgrade -g bower-away should help
