### ISSUE TITLE
Auto-init a package.json based on bower.json

### ISSUE THREAD

**Issue by FredKSchott** [sheerun/bower-away#2]
A user of will need to create a package.json to persist any bower2yarn transformations they make locally and start the transition from git urls to true npm packages. 

Since we have access to the bower.json and are already installing the necessary npm git dependencies, we should have everything we need to do this.

This should probably be an interactive experience similar to `yarn init` so that the user can walk through the new package.json, confirm all the information, and handle any conflicts that pop up (ex: `main: string[] -> main: string`).

**Comment by FredKSchott** [comment]
Happy to take a stab at this one, I've worked on a similar bower.json -> package.json conversion and already have a pretty good idea of what's required.

**Comment by evenstensberg** [comment]
Would be great @FredKSchott !

**Comment by sheerun** [comment]
@FredKSchott I'd be happy to review and merge your PR

**Comment by sheerun** [comment]
This is done
