### ISSUE TITLE
Can bower-away work with PNPM?

### ISSUE THREAD

**Issue by jefer94** [sheerun/bower-away#26]

**Comment by sheerun** [comment]
I doubt it, as package manger must be able to install bare repositories (i.e. without package.json), and resolve semver versions on git tags. Only Yarn passes this for now.

**Comment by jefer94** [comment]
Well, actually my environment are in webpack, and I don't need it, but from my point of view, to replace Bower was will be good, because it fail in updates some times, and I come from Yarn [5155](https://github.com/yarnpkg/yarn/issues/5155) and how can you see, I migrate from yarn, because it do much task for my development environment, also my procesador is laggy, I'd wait 5 minutes for command do a change. But for production environment with a server with checksums is the better for now.
