### ISSUE TITLE
Handling a bower git repo that contains a package.json

### ISSUE THREAD

**Issue by FredKSchott** [sheerun/bower-away#3]
If I understand Yarn/NPM's behavior correctly, when a git dependency is installed yarn will look for a  `package.json` in that repo. If one is found, it will treat it like a true npm dependency and go out and also install its `package.json` dependencies (and their deps, and their deps' deps, etc). This will apply to a ton of big projects, including [Mocha](https://github.com/mochajs/mocha), [Lodash](https://github.com/lodash/lodash), [Moment.js](https://github.com/moment/moment), and many more.

#### This is problematic for a few reasons:

- Bower is already expecting to install all dependencies itself inside of `/@bower_components/*`
- Could create duplicate npm dependencies already represented in `/@bower_components/*`
- Would make a flat install much more noisy, and introduce unnecessary conflicts to manually resolve
- other issues?

#### Potential solutions:

- Add option to yarn to ignore package.json if found in a git url
- other solutions?

**Comment by sheerun** [comment]
I think it's fine it's installing extra dependencies. This way it's easier
to start using these dependencies with webpack / cjs (they are immediately
available to "require")

**Comment by FredKSchott** [comment]
That would be a good thing if they were direct dependencies, but since they're transitive dependencies that's more of a footgun than anything (shouldn't be depended on indirectly).

The pain I'm expecting (that this issue is sort of getting at) is that we'll end up leaving our users with a package.json that technically works but is then stuck on git urls forever, unable to transition to true npm packages. Maybe that's out of scope for this project, but I don't think it should be.

**Comment by sheerun** [comment]
Bower packages depend on them just like Npm packages have dependencies.
You won't require them directly but requiring Bower/Npm packages requires
them. It's needed to properly deduplicate indirect dependencies when
bundling with something like webpack.

Switching to true npm package should be as simple as using require instead
of script, no?

I agree disabling installing indirect dependencies for Bower would make
migration easier (less conflicts), but I'm pretty sure Yarn won't go for it.

**Comment by FredKSchott** [comment]
Definitely not by default, but a niche flag could be acceptable to the yarn team. Definitely worth a reach out imo (but maybe not yet).

Do we want people to call `require('@bower_components/lodash')`? That's kind of the foot-gun I'm talking about, getting people to explicitly `yarn add lodash` then `require('lodash')` is a better habit to encourage.

Regardless, going through the entire flow with an actual real-world bower app would be a good litmus test to see how bad this could be. Having tried something similar, I'm worried it would be pretty bad, but maybe not. Maybe we don't turn on `flat: true` immediately, and leave that for the user to flip when they're ready?

**Comment by sheerun** [comment]
I think yes, we don't need to flatten npm dependencies, at least when
migrating, to make it easier to do so.
