### ISSUE TITLE
Handle Newer Versions of React

### ISSUE THREAD

**Issue by Aghassi** [sheerun/bower-away#5]
I'm only making an issue here so it doesn't get overlooked from this thread https://github.com/bower/bower/issues/2467

Essentially, the bower version of React contains `react-dom` in it: https://github.com/reactjs/react-bower

However, when you move to NPM you have to install `react`, `react-dom`, and `prop-types`. This script will not handle that. Maybe add a special case warning to output for now so people know? Or just make a special case that says "if react, ask if we need react-dom or prop-types" and force them to answer. Based on answer, we can add them to the resolution set.

**Comment by sheerun** [comment]
Well, this tool isn't about converting AMD/globals project to CommonJS project, but rather switching from bower to yarn. If one wants to switch to CJS version of react, an explicit change in package.json is necessary, followed by changes in code (i.e. require() instead of <script>)
