### ISSUE TITLE
can't covert dependencies on application/javascript resources

### ISSUE THREAD

**Issue by graingert** [sheerun/bower-away#6]
I've got a bower.json with an application/javascript resource:

```json
  "dependencies": {
    "some-module-name": "https://example.com/path/to/random/jsfile.js"
  }
```

This emits:

```json
{
  "dependencies": {
    "@bower_components/some-module-name": "https://example.com/path/to/random/jsfile.js#*"
  }
}
```

However yarn emits the following error:

```sh
error An unexpected error occurred: "https://example.com/path/to/random/jsfile.js: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?".
```

**Comment by graingert** [comment]
See also: https://github.com/yarnpkg/yarn/issues/1646

**Comment by sheerun** [comment]
I think there's no way around it as yarn doesn't support single .js files as dependencies, no?

**Comment by graingert** [comment]
Yup, I was wondering if you could help me with the RFC as you have more
clout

**Comment by sheerun** [comment]
I don't think yarn will accept is as such resources cannot be easily locked. e.g. this analytics.js can change every week and Yarn aims to be as deterministic as possible. Maybe it'd be better if bower2yarn downloaded such file to `vendor/analytics/index.js` upon conversion and reference as `file:vendor/analytics` in package.json.

**Comment by graingert** [comment]
Or maybe make a "bower light" for these edge cases and add it as an install
hook?

**Comment by sheerun** [comment]
I think bower2yarn can handle it as a conversion step (from bower.json to package.json)

**Comment by graingert** [comment]
Could just use wget with an install script?

**Comment by sheerun** [comment]
wget is not cross-platform and not always available

**Comment by sheerun** [comment]
plus wget on install is not deterministic

**Comment by graingert** [comment]
Oh I meant wget in the most general way. Could use axios/request to "web
get"

**Comment by sheerun** [comment]
still, it's not deterministic if it's in install script

**Comment by graingert** [comment]
Sure, it's better than not working at all. Especially to move people off of
bower

**Comment by sheerun** [comment]
bower2yarn could download this file to vendor/analytics/index.js

**Comment by sheerun** [comment]
@graingert Please add me as an owner of bower2yarn on https://www.npmjs.com as I can't publish it

**Comment by graingert** [comment]
Only if you promise never to publish a package.json with an unregistered
name to github ever again

**Comment by sheerun** [comment]
I didn't publish anything and I could change name of this script at any second, as it doesn't really matter. But given it's you who took this name, I think we can still publish it under bower2yarn :)

**Comment by graingert** [comment]
I'm happy to add you as a maintainer, I just need you to make that promise

**Comment by sheerun** [comment]
Sorry, I'm not in the mood

**Comment by JakeChampion** [comment]
@graingert Why did you take the name on npmjs if it wasn't to give it to this project?

**Comment by graingert** [comment]
Yes my intention is to give it to this project
