### ISSUE TITLE
Postinstall script not working on Windows Machine

### ISSUE THREAD

**Issue by ghost** [sheerun/bower-away#9]
> yarn install v1.1.0
> error An unexpected error occurred: "C:\\[path-to-project]\\package.json: Unexpected token @ in JSON at position 2255".
> 

"postinstall": "rm -rf bower_components && ln -sf node_modules\\@bower_components bower_components"

=> Maybe this is just a platform issue?
However, the suggested postinstall script should work on any plattform (maybe add a second line for Windows users?)

**Comment by sheerun** [comment]
This seems like an issue with JSON parsing, isn't it? Also indeed this script is suggested only for unix users. Please tell me if you manage to solve this issue.

**Comment by Willibaur** [comment]
@FlorianHanke-alphaQuest I think there is a typo in your command with `\` as you are using `\@bower_components` instead of `/@bower_components` , not sure if that solves your problem

**Comment by sheerun** [comment]
Fixed on master, we now recommend cross-platform command
